### ISSUE TITLE
Make video sticky on desktop so you can scroll the comments while still watching it

### ISSUE THREAD

**Issue by insin** [insin/control-panel-for-youtube#17]

**Comment by insin** [comment]
This CSS unsticks the header, makes the video half of view height and allows comments to scroll underneath it

- Requires Cinema mode
- The video needs to be forced to reflow after the style is applied

```css
ytd-watch-flexy[full-bleed-player] #full-bleed-container.ytd-watch-flexy {
  max-height: 50vh;
  aspect-ratio: 16/9;
  position: sticky;
  top: 0;
  /* Display video on top of scrolled content */
  /* This specific value is needed to cover the channel name */
  z-index: 301;
  min-height: unset;
}

#masthead-container.ytd-app {
  position: static;
}

#page-manager.ytd-app {
  margin-top: 0 !important;
}
```

![Screenshot 2024-03-30 at 10 41 20 pm](https://github.com/insin/control-panel-for-youtube/assets/226692/67da81a0-8d1e-46ac-9717-eb7c4b178c52)
