### ISSUE TITLE
Search thumbails have been made larger on desktop

### ISSUE THREAD

**Issue by insin** [insin/control-panel-for-youtube#35]
This is the CSS for this recent change:

```css
ytd-video-renderer[use-bigger-thumbs][bigger-thumbs-style="BIG"] ytd-thumbnail.ytd-video-renderer {
  max-width: 500px;
  min-width: 240px;
}
```

![Screenshot 2024-03-31 at 1 34 24 am](https://github.com/insin/control-panel-for-youtube/assets/226692/5e4e3479-8246-4b67-889d-1d879404ca82)

Override to restore the old width:

```css
ytd-video-renderer[use-bigger-thumbs][bigger-thumbs-style="BIG"] ytd-thumbnail.ytd-video-renderer {
  max-width: 400px;
}
```

![Screenshot 2024-03-31 at 1 34 08 am](https://github.com/insin/control-panel-for-youtube/assets/226692/2f578d5a-53a2-4ccc-a0c0-d9a797e504e2)
