### ISSUE TITLE
Spacing of Home/Subscriptions grid items on desktop is off

### ISSUE THREAD

**Issue by insin** [insin/control-panel-for-youtube#47]
YouTube's new grid implementation uses an `is-in-first-column` attribute to apply more `margin-left`.

```css
ytd-rich-item-renderer[rendered-from-rich-grid][is-in-first-column] {
  margin-left: calc(var(--ytd-rich-grid-item-margin)/2 + var(--ytd-rich-grid-gutter-margin));
}
```

This results in inconsistent spacing and gaps when we hide some items and make the rest flow together:

![Screenshot 2024-08-04 at 3 40 56 PM](https://github.com/user-attachments/assets/7e7bbf2c-2d26-4c21-94df-6e08b2a615ed)

We could apply uniform `margin-left` and use padding or margin on a container for the gutter, but I assume there's a reason they haven't done that.
