### ISSUE TITLE
Add an option to make the Default view larger for watching playlists

### ISSUE THREAD

**Issue by insin** [insin/control-panel-for-youtube#49]
WIP example:

![Screenshot 2024-08-05 at 4 21 37 PM](https://github.com/user-attachments/assets/5cdaf791-b355-4a20-9dd7-4e244d65a7fc)

TODO:

- Max widths which have been removed should be applied to `#below`
- Player controls need to be adjusted for the new size

```css
ytd-watch-flexy[flexy]:not([full-bleed-player][full-bleed-no-max-width-columns])
#columns.ytd-watch-flexy {
  max-width: none !important;
}
ytd-watch-flexy[flexy][is-two-columns_][is-four-three-to-sixteen-nine-video_]:not([full-bleed-player][full-bleed-no-max-width-columns]):not([fixed-panels])
#primary.ytd-watch-flexy {
  max-width: none !important;
  margin-left: 0 !important;
  padding-right: 12px !important;
  padding-top: 0 !important;
}
ytd-watch-flexy[flexy] #player-container-outer.ytd-watch-flexy {
  max-width: none !important;
}
ytd-watch-flexy[flexy][is-two-columns_][is-four-three-to-sixteen-nine-video_]:not([full-bleed-player][full-bleed-no-max-width-columns]):not([fixed-panels])
video {
  width: 100% !important;
  height: auto !important;
}
ytd-watch-flexy[default-layout]:not([no-top-margin]):not([reduced-top-margin])
#secondary.ytd-watch-flexy {
  padding-right: 12px !important;
  padding-top: 0 !important;
}
```
